### ISSUE TITLE
Visual Studio Code - Insiders: Projects file not found

### ISSUE THREAD

**Issue by Sillium** [kbshl/alfred-vs-code#3]
I can see, you already have a TODO in [vsc.js:44](https://github.com/konstantinbueschel/alfred-vs-code/blob/c2549659cbd0cc5ecf18556c86e5a3810a575c64/vsc.js#L44) for this. Any news on that? If I find the time, I'll see if I can make it work and create a Pull Request. Just wanted to make sure, it's really not working yet with your code in comments.

**Comment by kbshl** [comment]
Version 1.1.0 containing PR #6 from @kaibrueckers 👍 just released
